FROM mcr.microsoft.com/playwright:v1.59.1-noble
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY apps/frontend/package*.json ./apps/frontend/
RUN npm ci --prefix apps/frontend
CMD ["npm", "run", "test:e2e"]
