package com.todo.model;

public enum AuditActionType {
    TODO_CREATED,
    TODO_UPDATED,
    TODO_DELETED,
    USER_REGISTERED,
    USER_LOGIN,
    ADMIN_DELETE_USER,
    ADMIN_RESET_PASSWORD,
    UNAUTHENTICATED,
    ACCESS_DENIED,
    TODO_SHARED
}
